import { User } from './../auth/user.entity';
import { TaskStatus } from './task-status.enum';
import { BaseEntity, Column, Entity, ManyToOne, PrimaryGeneratedColumn } from "typeorm";

@Entity()
export class Task extends BaseEntity{

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    title: String;

    @Column()
    description: string;

    @Column()
    status: TaskStatus

    // adding it - such that user can access only those tasks that they have created
    @ManyToOne( type => User, user => user.tasks, { eager: false } )
    user: User;

    // It is automatically generated by typeORM 
    // It is usefull to access task associated with userID
    @Column()
    userId: number;
}